name: StyleTP
version: 2.0
author: [Marti201, sidey383]
main: me.marti201.styletp.StyleTP
commands:
  styletp:
    usage: /styletp
    description: Toggles teleportation effects
    aliases: stp
permissions:
  styletp.use:
    default: true